#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

// Keep console environment aligned with web entrypoint and runtime env vars.
$appEnv = strtolower((string) (getenv('YII_ENV') ?: getenv('APP_ENV') ?: 'prod'));
if (in_array($appEnv, ['dev', 'development', 'local'], true)) {
    $yiiEnv = 'dev';
} elseif (in_array($appEnv, ['test', 'testing'], true)) {
    $yiiEnv = 'test';
} else {
    $yiiEnv = 'prod';
}

$debugEnv = getenv('YII_DEBUG');
if ($debugEnv === false || $debugEnv === '') {
    $yiiDebug = ($yiiEnv === 'dev');
} else {
    $yiiDebug = filter_var($debugEnv, FILTER_VALIDATE_BOOLEAN);
}

defined('YII_DEBUG') or define('YII_DEBUG', $yiiDebug);
defined('YII_ENV') or define('YII_ENV', $yiiEnv);
defined('YII_ENV_DEV') or define('YII_ENV_DEV', YII_ENV === 'dev');
defined('YII_ENV_PROD') or define('YII_ENV_PROD', YII_ENV === 'prod');
defined('YII_ENV_TEST') or define('YII_ENV_TEST', YII_ENV === 'test');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
